---
# Job template - to be used in a pipeline by including this file.
# Make sure to include the .sast stage in the pipeline template
#
# Detects secrets in modified files
#
# include:
#  - .gitlab/detect-secrets.gitlab-ci.yml

detect-secrets:
  extends: .sast
  image: gofwd/tools-image
  script:
    - mkdir -p reports &>/dev/null
    - rm -rf reports/detect-secrets-report.txt &>/dev/null
    - >
      if [ "$CI_COMMIT_BEFORE_SHA" = "0000000000000000000000000000000000000000" ]; then
      COMMIT_BEFORE_SHA=$(git rev-parse HEAD~1);
      else
      COMMIT_BEFORE_SHA=$CI_COMMIT_BEFORE_SHA;
      fi
    - >-
      echo "Checking the following files for secrets:
      $(git diff --name-only $COMMIT_BEFORE_SHA $CI_COMMIT_SHA)"
    - >
      git diff --name-only $COMMIT_BEFORE_SHA $CI_COMMIT_SHA |
      xargs detect-secrets-hook --baseline .detect-secrets.json |
      tee reports/detect-secrets-report.txt
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - reports/detect-secrets-report.txt
